export const ERROR_CODES = {
  // Auth
  OTP_LOCKED: 'OTP_LOCKED',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_BLACKLISTED: 'TOKEN_BLACKLISTED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  INVALID_TOKEN_PAYLOAD: 'INVALID_TOKEN_PAYLOAD',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // KYC
  KYC_NOT_VERIFIED: 'KYC_NOT_VERIFIED',
  AADHAAR_NOT_VERIFIED: 'AADHAAR_NOT_VERIFIED',
  AADHAAR_MISMATCH: 'AADHAAR_MISMATCH',
  INVALID_KYC_SESSION: 'INVALID_KYC_SESSION',

  // Consent
  CONSENT_ALREADY_ACTIVE: 'CONSENT_ALREADY_ACTIVE',
  CONSENT_NOT_FOUND: 'CONSENT_NOT_FOUND',

  // Document
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',

  // Scoring
  SCORE_NOT_GENERATED: 'SCORE_NOT_GENERATED',
  SCORING_SERVICE_UNAVAILABLE: 'SCORING_SERVICE_UNAVAILABLE',

  // Loan
  ACTIVE_LOAN_EXISTS: 'ACTIVE_LOAN_EXISTS',
  INVALID_LOAN_TRANSITION: 'INVALID_LOAN_TRANSITION',
  LOAN_NOT_FOUND: 'LOAN_NOT_FOUND',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};
