import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1780607085333 implements MigrationInterface {
    name = 'Init1780607085333'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_referred_by_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_actor_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "sessions_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "cms_content" DROP CONSTRAINT "cms_content_updated_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "cms_content" DROP CONSTRAINT "cms_content_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "consent_records" DROP CONSTRAINT "consent_records_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "documents_verified_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "documents_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "kyc_records" DROP CONSTRAINT "kyc_records_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "credit_scores" DROP CONSTRAINT "credit_scores_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "loan_applications" DROP CONSTRAINT "loan_applications_second_approver_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "loan_applications" DROP CONSTRAINT "loan_applications_lender_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "loan_applications" DROP CONSTRAINT "loan_applications_score_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "loan_applications" DROP CONSTRAINT "loan_applications_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" DROP CONSTRAINT "emi_schedules_loan_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "loan_state_transitions" DROP CONSTRAINT "loan_state_transitions_actor_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "loan_state_transitions" DROP CONSTRAINT "loan_state_transitions_loan_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "repayment_events" DROP CONSTRAINT "repayment_events_emi_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "repayment_events" DROP CONSTRAINT "repayment_events_loan_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_user_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_mobile"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_role_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_deletion_scheduled"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_entity"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_actor"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_action"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sessions_jti"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sessions_refresh"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sessions_user_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sessions_expires"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cms_key_locale"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cms_namespace"`);
        await queryRunner.query(`DROP INDEX "public"."idx_faq_category_locale"`);
        await queryRunner.query(`DROP INDEX "public"."idx_consent_user_source"`);
        await queryRunner.query(`DROP INDEX "public"."idx_consent_deletion"`);
        await queryRunner.query(`DROP INDEX "public"."idx_consent_expiry"`);
        await queryRunner.query(`DROP INDEX "public"."idx_docs_user_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_docs_hard_delete"`);
        await queryRunner.query(`DROP INDEX "public"."idx_docs_hash"`);
        await queryRunner.query(`DROP INDEX "public"."idx_kyc_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_kyc_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_scores_user_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_scores_band"`);
        await queryRunner.query(`DROP INDEX "public"."idx_scores_model"`);
        await queryRunner.query(`DROP INDEX "public"."idx_loans_user_state"`);
        await queryRunner.query(`DROP INDEX "public"."idx_loans_lender_state"`);
        await queryRunner.query(`DROP INDEX "public"."idx_loans_submitted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_loans_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_loans_band"`);
        await queryRunner.query(`DROP INDEX "public"."idx_emi_loan"`);
        await queryRunner.query(`DROP INDEX "public"."idx_emi_due"`);
        await queryRunner.query(`DROP INDEX "public"."idx_emi_overdue"`);
        await queryRunner.query(`DROP INDEX "public"."idx_repayment_loan"`);
        await queryRunner.query(`DROP INDEX "public"."idx_repayment_emi"`);
        await queryRunner.query(`DROP INDEX "public"."idx_repayment_unreconciled"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notif_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notif_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notif_retry"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_onboarding_step_check"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "documents_size_bytes_check"`);
        await queryRunner.query(`ALTER TABLE "kyc_records" DROP CONSTRAINT "kyc_records_face_match_score_check"`);
        await queryRunner.query(`ALTER TABLE "credit_scores" DROP CONSTRAINT "credit_scores_score_check"`);
        await queryRunner.query(`ALTER TABLE "credit_scores" DROP CONSTRAINT "credit_scores_model1_pd_check"`);
        await queryRunner.query(`ALTER TABLE "credit_scores" DROP CONSTRAINT "credit_scores_model2_risk_check"`);
        await queryRunner.query(`ALTER TABLE "credit_scores" DROP CONSTRAINT "credit_scores_model3_stability_check"`);
        await queryRunner.query(`ALTER TABLE "credit_scores" DROP CONSTRAINT "credit_scores_ensemble_pd_check"`);
        await queryRunner.query(`ALTER TABLE "loan_applications" DROP CONSTRAINT "loan_applications_amount_requested_check"`);
        await queryRunner.query(`ALTER TABLE "loan_applications" DROP CONSTRAINT "loan_applications_amount_approved_check"`);
        await queryRunner.query(`ALTER TABLE "loan_applications" DROP CONSTRAINT "loan_applications_tenure_months_check"`);
        await queryRunner.query(`ALTER TABLE "loan_applications" DROP CONSTRAINT "loan_applications_interest_rate_check"`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" DROP CONSTRAINT "emi_schedules_installment_number_check"`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" DROP CONSTRAINT "emi_schedules_principal_amount_check"`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" DROP CONSTRAINT "emi_schedules_interest_amount_check"`);
        await queryRunner.query(`ALTER TABLE "loan_state_transitions" DROP CONSTRAINT "valid_transition"`);
        await queryRunner.query(`ALTER TABLE "repayment_events" DROP CONSTRAINT "repayment_events_amount_paid_check"`);
        await queryRunner.query(`ALTER TABLE "cms_content" DROP CONSTRAINT "cms_content_key_locale_key"`);
        await queryRunner.query(`ALTER TABLE "cms_questionnaire_questions" DROP CONSTRAINT "cms_questionnaire_questions_version_q_number_key"`);
        await queryRunner.query(`ALTER TABLE "consent_records" DROP CONSTRAINT "consent_records_user_id_data_source_is_active_key"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "documents_user_id_doc_type_is_deleted_key"`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" DROP CONSTRAINT "emi_schedules_loan_id_installment_number_key"`);
        await queryRunner.query(`COMMENT ON TABLE "users" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."mobile_number" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."full_name_encrypted" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."user_role" RENAME TO "user_role_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('borrower', 'lender', 'admin', 'compliance', 'support')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'borrower'`);
        await queryRunner.query(`DROP TYPE "public"."user_role_old"`);
        await queryRunner.query(`ALTER TYPE "public"."user_status" RENAME TO "user_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('pending', 'active', 'suspended', 'deleted', 'banned')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" TYPE "public"."users_status_enum" USING "status"::"text"::"public"."users_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."user_status_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."deletion_scheduled_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "cms_loan_products" DROP COLUMN "eligible_risk_bands"`);
        await queryRunner.query(`DROP TYPE "public"."risk_band"`);
        await queryRunner.query(`ALTER TABLE "cms_loan_products" ADD "eligible_risk_bands" text array NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cms_questionnaire_questions" ALTER COLUMN "weight" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TYPE "public"."data_source" RENAME TO "data_source_old"`);
        await queryRunner.query(`CREATE TYPE "public"."consent_records_data_source_enum" AS ENUM('phone', 'bank', 'ecommerce', 'geolocation', 'merchant', 'psychometric')`);
        await queryRunner.query(`ALTER TABLE "consent_records" ALTER COLUMN "data_source" TYPE "public"."consent_records_data_source_enum" USING "data_source"::"text"::"public"."consent_records_data_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."data_source_old"`);
        await queryRunner.query(`ALTER TYPE "public"."consent_scope" RENAME TO "consent_scope_old"`);
        await queryRunner.query(`CREATE TYPE "public"."consent_records_scope_enum" AS ENUM('read', 'read_aggregate', 'read_process')`);
        await queryRunner.query(`ALTER TABLE "consent_records" ALTER COLUMN "scope" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "consent_records" ALTER COLUMN "scope" TYPE "public"."consent_records_scope_enum" USING "scope"::"text"::"public"."consent_records_scope_enum"`);
        await queryRunner.query(`ALTER TABLE "consent_records" ALTER COLUMN "scope" SET DEFAULT 'read'`);
        await queryRunner.query(`DROP TYPE "public"."consent_scope_old"`);
        await queryRunner.query(`ALTER TABLE "consent_records" ALTER COLUMN "valid_until" DROP DEFAULT`);
        await queryRunner.query(`ALTER TYPE "public"."doc_type" RENAME TO "doc_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."documents_doc_type_enum" AS ENUM('aadhaar_front', 'aadhaar_back', 'pan', 'bank_statement', 'income_proof', 'itr', 'selfie', 'selfie_with_id', 'business_reg', 'gst_certificate', 'udyam_certificate', 'trade_licence')`);
        await queryRunner.query(`ALTER TABLE "documents" ALTER COLUMN "doc_type" TYPE "public"."documents_doc_type_enum" USING "doc_type"::"text"::"public"."documents_doc_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."doc_type_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "documents"."s3_key_encrypted" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "documents"."file_hash" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "documents"."retention_years" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "kyc_records"."aadhaar_hash" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."kyc_status" RENAME TO "kyc_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."kyc_records_verification_status_enum" AS ENUM('pending', 'aadhaar_verified', 'pan_verified', 'fully_verified', 'liveness_passed', 'failed', 'expired')`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ALTER COLUMN "verification_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ALTER COLUMN "verification_status" TYPE "public"."kyc_records_verification_status_enum" USING "verification_status"::"text"::"public"."kyc_records_verification_status_enum"`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ALTER COLUMN "verification_status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."kyc_status_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "kyc_records"."extracted_data_encrypted" IS NULL`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ALTER COLUMN "expires_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TYPE "public"."risk_band" RENAME TO "risk_band_old"`);
        await queryRunner.query(`CREATE TYPE "public"."credit_scores_risk_band_enum" AS ENUM('very_high', 'high', 'medium', 'low', 'very_low')`);
        await queryRunner.query(`ALTER TABLE "credit_scores" ALTER COLUMN "risk_band" TYPE "public"."credit_scores_risk_band_enum" USING "risk_band"::"text"::"public"."credit_scores_risk_band_enum"`);
        await queryRunner.query(`DROP TYPE "public"."risk_band_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "credit_scores"."shap_values" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "credit_scores"."features_snapshot" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "loan_applications"."amount_requested" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."loan_purpose" RENAME TO "loan_purpose_old"`);
        await queryRunner.query(`CREATE TYPE "public"."loan_applications_purpose_enum" AS ENUM('working_capital', 'equipment_purchase', 'inventory', 'business_expansion', 'personal_emergency', 'education', 'medical', 'home_improvement', 'agriculture', 'other')`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ALTER COLUMN "purpose" TYPE "public"."loan_applications_purpose_enum" USING "purpose"::"text"::"public"."loan_applications_purpose_enum"`);
        await queryRunner.query(`DROP TYPE "public"."loan_purpose_old"`);
        await queryRunner.query(`ALTER TYPE "public"."loan_state" RENAME TO "loan_state_old"`);
        await queryRunner.query(`CREATE TYPE "public"."loan_applications_state_enum" AS ENUM('draft', 'submitted', 'under_review', 'pending_second_approval', 'approved', 'rejected', 'disbursed', 'repaying', 'closed', 'defaulted', 'written_off')`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ALTER COLUMN "state" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ALTER COLUMN "state" TYPE "public"."loan_applications_state_enum" USING "state"::"text"::"public"."loan_applications_state_enum"`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ALTER COLUMN "state" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."loan_state_old"`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ALTER COLUMN "processing_fee" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "loan_applications"."disbursement_account" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."emi_status" RENAME TO "emi_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."emi_schedules_status_enum" AS ENUM('pending', 'paid', 'partially_paid', 'late', 'waived', 'defaulted')`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" ALTER COLUMN "status" TYPE "public"."emi_schedules_status_enum" USING "status"::"text"::"public"."emi_schedules_status_enum"`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."emi_status_old"`);
        await queryRunner.query(`ALTER TYPE "public"."loan_state" RENAME TO "loan_state_old"`);
        await queryRunner.query(`CREATE TYPE "public"."loan_state_transitions_from_state_enum" AS ENUM('draft', 'submitted', 'under_review', 'pending_second_approval', 'approved', 'rejected', 'disbursed', 'repaying', 'closed', 'defaulted', 'written_off')`);
        await queryRunner.query(`ALTER TABLE "loan_state_transitions" ALTER COLUMN "from_state" TYPE "public"."loan_state_transitions_from_state_enum" USING "from_state"::"text"::"public"."loan_state_transitions_from_state_enum"`);
        await queryRunner.query(`DROP TYPE "public"."loan_state_old"`);
        await queryRunner.query(`ALTER TYPE "public"."loan_state" RENAME TO "loan_state_old"`);
        await queryRunner.query(`CREATE TYPE "public"."loan_state_transitions_to_state_enum" AS ENUM('draft', 'submitted', 'under_review', 'pending_second_approval', 'approved', 'rejected', 'disbursed', 'repaying', 'closed', 'defaulted', 'written_off')`);
        await queryRunner.query(`ALTER TABLE "loan_state_transitions" ALTER COLUMN "to_state" TYPE "public"."loan_state_transitions_to_state_enum" USING "to_state"::"text"::"public"."loan_state_transitions_to_state_enum"`);
        await queryRunner.query(`DROP TYPE "public"."loan_state_old"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_mode" RENAME TO "payment_mode_old"`);
        await queryRunner.query(`CREATE TYPE "public"."repayment_events_payment_mode_enum" AS ENUM('imps', 'neft', 'rtgs', 'upi', 'nach', 'cash', 'cheque')`);
        await queryRunner.query(`ALTER TABLE "repayment_events" ALTER COLUMN "payment_mode" TYPE "public"."repayment_events_payment_mode_enum" USING "payment_mode"::"text"::"public"."repayment_events_payment_mode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_mode_old"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_channel" RENAME TO "notification_channel_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('sms', 'whatsapp', 'email', 'push', 'in_app')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "channel" TYPE "public"."notifications_channel_enum" USING "channel"::"text"::"public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_channel_old"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_status" RENAME TO "notification_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('queued', 'processing', 'sent', 'delivered', 'failed', 'bounced')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "status" TYPE "public"."notifications_status_enum" USING "status"::"text"::"public"."notifications_status_enum"`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "status" SET DEFAULT 'queued'`);
        await queryRunner.query(`DROP TYPE "public"."notification_status_old"`);
        await queryRunner.query(`CREATE INDEX "IDX_c9b5b525a96ddc2c5647d7f7fa" ON "users"  ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6ee2d4bf901675877bb94977c" ON "users"  ("role", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2ff13f7845caee9f24ce52e456" ON "audit_logs"  ("action", "logged_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_1857577055a7ef3b81119fffb5" ON "audit_logs"  ("actor_id", "logged_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_267676c16f82b3db77cfc8e309" ON "audit_logs"  ("entity_type", "entity_id", "logged_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d6185b2849a1e4d0c067a57ca8" ON "sessions"  ("refresh_token_hash") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_107b2886fda198e2da45bb8f07" ON "sessions"  ("jwt_jti") `);
        await queryRunner.query(`CREATE INDEX "IDX_634ed581a282d6b9feaf23d0a5" ON "cms_content"  ("namespace", "locale") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0a56cf83c07e8f132fa6dba58" ON "cms_faqs"  ("category", "locale") `);
        await queryRunner.query(`CREATE INDEX "IDX_731632e329488f4eca18e3e880" ON "consent_records"  ("user_id", "data_source", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_fc721409097fc82b501cc0df44" ON "documents"  ("user_id", "doc_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_21753efb9d92f6c91c99fe3a32" ON "kyc_records"  ("verification_status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d20b5a5f164a27f1a823596d19" ON "kyc_records"  ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1b0a01cca21910160a5c2a71bb" ON "credit_scores"  ("model_version", "generated_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4009570beae9c189fe7f1c743" ON "credit_scores"  ("risk_band", "generated_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e370b8fa9a138dc6079a99023" ON "credit_scores"  ("user_id", "generated_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_48bec22f5ce14511c38695a86e" ON "loan_applications"  ("lender_id", "state", "applied_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe1c330c2223fedc2f3e80447d" ON "loan_applications"  ("user_id", "state") `);
        await queryRunner.query(`CREATE INDEX "IDX_744bdbe16396b4ff6cba3be21c" ON "emi_schedules"  ("due_date", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7632eeb96ea8f6656a996a4a6" ON "emi_schedules"  ("loan_id", "installment_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_59eef209656080d86543c2fe15" ON "loan_state_transitions"  ("loan_id", "transitioned_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3b27f169937a1d7dd9a6f0768" ON "repayment_events"  ("emi_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e8f5924f658ae1df8016940ee1" ON "repayment_events"  ("loan_id", "paid_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_c0469cda2f63d7311fd65996d9" ON "notifications"  ("status", "scheduled_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_310667f935698fcd8cb319113a" ON "notifications"  ("user_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "cms_content" ADD CONSTRAINT "UQ_2ea1488286719bed4fbdf984e9d" UNIQUE ("key", "locale")`);
        await queryRunner.query(`ALTER TABLE "cms_questionnaire_questions" ADD CONSTRAINT "UQ_078bc3e4456eca34bf478dff8cc" UNIQUE ("version", "q_number")`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" ADD CONSTRAINT "UQ_a7632eeb96ea8f6656a996a4a64" UNIQUE ("loan_id", "installment_number")`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a78a00605c95ca6737389f6360b" FOREIGN KEY ("referred_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_177183f29f438c488b5e8510cdb" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cms_content" ADD CONSTRAINT "FK_ad010ee6edaca3b78e813636837" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cms_content" ADD CONSTRAINT "FK_2aa50c43e0cda64c6566d8c80bd" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consent_records" ADD CONSTRAINT "FK_b823aad0deceda10806be9aa447" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_c7481daf5059307842edef74d73" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_647be7c22f279b5747c243303de" FOREIGN KEY ("verified_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ADD CONSTRAINT "FK_d20b5a5f164a27f1a823596d192" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_scores" ADD CONSTRAINT "FK_eec2f48ca72587535deef8d7254" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ADD CONSTRAINT "FK_675fc88c789366e3f362ebbccb3" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ADD CONSTRAINT "FK_b3aa1634069524f581f3bdd0716" FOREIGN KEY ("score_id") REFERENCES "credit_scores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ADD CONSTRAINT "FK_f688ff36f884bd89bfd721d3ff2" FOREIGN KEY ("lender_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ADD CONSTRAINT "FK_27fc67226b5c82648de69cda663" FOREIGN KEY ("second_approver_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" ADD CONSTRAINT "FK_475252c543810da3126e07058c6" FOREIGN KEY ("loan_id") REFERENCES "loan_applications"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_state_transitions" ADD CONSTRAINT "FK_ec36a9e2bed338f5149d54ab652" FOREIGN KEY ("loan_id") REFERENCES "loan_applications"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_state_transitions" ADD CONSTRAINT "FK_6796639bb7eadffcbaec224cbf1" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repayment_events" ADD CONSTRAINT "FK_13684aa4281994c1f1d93145712" FOREIGN KEY ("loan_id") REFERENCES "loan_applications"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repayment_events" ADD CONSTRAINT "FK_f3b27f169937a1d7dd9a6f0768e" FOREIGN KEY ("emi_id") REFERENCES "emi_schedules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "repayment_events" DROP CONSTRAINT "FK_f3b27f169937a1d7dd9a6f0768e"`);
        await queryRunner.query(`ALTER TABLE "repayment_events" DROP CONSTRAINT "FK_13684aa4281994c1f1d93145712"`);
        await queryRunner.query(`ALTER TABLE "loan_state_transitions" DROP CONSTRAINT "FK_6796639bb7eadffcbaec224cbf1"`);
        await queryRunner.query(`ALTER TABLE "loan_state_transitions" DROP CONSTRAINT "FK_ec36a9e2bed338f5149d54ab652"`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" DROP CONSTRAINT "FK_475252c543810da3126e07058c6"`);
        await queryRunner.query(`ALTER TABLE "loan_applications" DROP CONSTRAINT "FK_27fc67226b5c82648de69cda663"`);
        await queryRunner.query(`ALTER TABLE "loan_applications" DROP CONSTRAINT "FK_f688ff36f884bd89bfd721d3ff2"`);
        await queryRunner.query(`ALTER TABLE "loan_applications" DROP CONSTRAINT "FK_b3aa1634069524f581f3bdd0716"`);
        await queryRunner.query(`ALTER TABLE "loan_applications" DROP CONSTRAINT "FK_675fc88c789366e3f362ebbccb3"`);
        await queryRunner.query(`ALTER TABLE "credit_scores" DROP CONSTRAINT "FK_eec2f48ca72587535deef8d7254"`);
        await queryRunner.query(`ALTER TABLE "kyc_records" DROP CONSTRAINT "FK_d20b5a5f164a27f1a823596d192"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_647be7c22f279b5747c243303de"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_c7481daf5059307842edef74d73"`);
        await queryRunner.query(`ALTER TABLE "consent_records" DROP CONSTRAINT "FK_b823aad0deceda10806be9aa447"`);
        await queryRunner.query(`ALTER TABLE "cms_content" DROP CONSTRAINT "FK_2aa50c43e0cda64c6566d8c80bd"`);
        await queryRunner.query(`ALTER TABLE "cms_content" DROP CONSTRAINT "FK_ad010ee6edaca3b78e813636837"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_177183f29f438c488b5e8510cdb"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a78a00605c95ca6737389f6360b"`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" DROP CONSTRAINT "UQ_a7632eeb96ea8f6656a996a4a64"`);
        await queryRunner.query(`ALTER TABLE "cms_questionnaire_questions" DROP CONSTRAINT "UQ_078bc3e4456eca34bf478dff8cc"`);
        await queryRunner.query(`ALTER TABLE "cms_content" DROP CONSTRAINT "UQ_2ea1488286719bed4fbdf984e9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_310667f935698fcd8cb319113a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0469cda2f63d7311fd65996d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e8f5924f658ae1df8016940ee1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3b27f169937a1d7dd9a6f0768"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59eef209656080d86543c2fe15"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7632eeb96ea8f6656a996a4a6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_744bdbe16396b4ff6cba3be21c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe1c330c2223fedc2f3e80447d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48bec22f5ce14511c38695a86e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e370b8fa9a138dc6079a99023"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a4009570beae9c189fe7f1c743"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b0a01cca21910160a5c2a71bb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d20b5a5f164a27f1a823596d19"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21753efb9d92f6c91c99fe3a32"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc721409097fc82b501cc0df44"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_731632e329488f4eca18e3e880"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0a56cf83c07e8f132fa6dba58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_634ed581a282d6b9feaf23d0a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_107b2886fda198e2da45bb8f07"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6185b2849a1e4d0c067a57ca8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_267676c16f82b3db77cfc8e309"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1857577055a7ef3b81119fffb5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ff13f7845caee9f24ce52e456"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6ee2d4bf901675877bb94977c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9b5b525a96ddc2c5647d7f7fa"`);
        await queryRunner.query(`CREATE TYPE "public"."notification_status_old" AS ENUM('queued', 'processing', 'sent', 'delivered', 'failed', 'bounced')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "status" TYPE "public"."notification_status_old" USING "status"::"text"::"public"."notification_status_old"`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "status" SET DEFAULT 'queued'`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_status_old" RENAME TO "notification_status"`);
        await queryRunner.query(`CREATE TYPE "public"."notification_channel_old" AS ENUM('sms', 'whatsapp', 'email', 'push', 'in_app')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "channel" TYPE "public"."notification_channel_old" USING "channel"::"text"::"public"."notification_channel_old"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_channel_old" RENAME TO "notification_channel"`);
        await queryRunner.query(`CREATE TYPE "public"."payment_mode_old" AS ENUM('imps', 'neft', 'rtgs', 'upi', 'nach', 'cash', 'cheque')`);
        await queryRunner.query(`ALTER TABLE "repayment_events" ALTER COLUMN "payment_mode" TYPE "public"."payment_mode_old" USING "payment_mode"::"text"::"public"."payment_mode_old"`);
        await queryRunner.query(`DROP TYPE "public"."repayment_events_payment_mode_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_mode_old" RENAME TO "payment_mode"`);
        await queryRunner.query(`CREATE TYPE "public"."loan_state_old" AS ENUM('draft', 'submitted', 'under_review', 'pending_second_approval', 'approved', 'rejected', 'disbursed', 'repaying', 'closed', 'defaulted', 'written_off')`);
        await queryRunner.query(`ALTER TABLE "loan_state_transitions" ALTER COLUMN "to_state" TYPE "public"."loan_state_old" USING "to_state"::"text"::"public"."loan_state_old"`);
        await queryRunner.query(`DROP TYPE "public"."loan_state_transitions_to_state_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."loan_state_old" RENAME TO "loan_state"`);
        await queryRunner.query(`CREATE TYPE "public"."loan_state_old" AS ENUM('draft', 'submitted', 'under_review', 'pending_second_approval', 'approved', 'rejected', 'disbursed', 'repaying', 'closed', 'defaulted', 'written_off')`);
        await queryRunner.query(`ALTER TABLE "loan_state_transitions" ALTER COLUMN "from_state" TYPE "public"."loan_state_old" USING "from_state"::"text"::"public"."loan_state_old"`);
        await queryRunner.query(`DROP TYPE "public"."loan_state_transitions_from_state_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."loan_state_old" RENAME TO "loan_state"`);
        await queryRunner.query(`CREATE TYPE "public"."emi_status_old" AS ENUM('pending', 'paid', 'partially_paid', 'late', 'waived', 'defaulted')`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" ALTER COLUMN "status" TYPE "public"."emi_status_old" USING "status"::"text"::"public"."emi_status_old"`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."emi_schedules_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."emi_status_old" RENAME TO "emi_status"`);
        await queryRunner.query(`COMMENT ON COLUMN "loan_applications"."disbursement_account" IS 'Encrypted beneficiary account details.'`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ALTER COLUMN "processing_fee" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."loan_state_old" AS ENUM('draft', 'submitted', 'under_review', 'pending_second_approval', 'approved', 'rejected', 'disbursed', 'repaying', 'closed', 'defaulted', 'written_off')`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ALTER COLUMN "state" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ALTER COLUMN "state" TYPE "public"."loan_state_old" USING "state"::"text"::"public"."loan_state_old"`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ALTER COLUMN "state" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."loan_applications_state_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."loan_state_old" RENAME TO "loan_state"`);
        await queryRunner.query(`CREATE TYPE "public"."loan_purpose_old" AS ENUM('working_capital', 'equipment_purchase', 'inventory', 'business_expansion', 'personal_emergency', 'education', 'medical', 'home_improvement', 'agriculture', 'other')`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ALTER COLUMN "purpose" TYPE "public"."loan_purpose_old" USING "purpose"::"text"::"public"."loan_purpose_old"`);
        await queryRunner.query(`DROP TYPE "public"."loan_applications_purpose_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."loan_purpose_old" RENAME TO "loan_purpose"`);
        await queryRunner.query(`COMMENT ON COLUMN "loan_applications"."amount_requested" IS 'In Indian Paise (1 INR = 100 paise) for precision. Display as INR/100.'`);
        await queryRunner.query(`COMMENT ON COLUMN "credit_scores"."features_snapshot" IS 'Snapshot of all 40+ feature values at time of scoring. Used for model auditing.'`);
        await queryRunner.query(`COMMENT ON COLUMN "credit_scores"."shap_values" IS 'Array of {feature, contribution, direction, value, percentile} objects.'`);
        await queryRunner.query(`CREATE TYPE "public"."risk_band_old" AS ENUM('very_high', 'high', 'medium', 'low', 'very_low')`);
        await queryRunner.query(`ALTER TABLE "credit_scores" ALTER COLUMN "risk_band" TYPE "public"."risk_band_old" USING "risk_band"::"text"::"public"."risk_band_old"`);
        await queryRunner.query(`DROP TYPE "public"."credit_scores_risk_band_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."risk_band_old" RENAME TO "risk_band"`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ALTER COLUMN "expires_at" SET DEFAULT (now() + '1 year')`);
        await queryRunner.query(`COMMENT ON COLUMN "kyc_records"."extracted_data_encrypted" IS 'Encrypted JSONB: name, dob, address, gender. Never plaintext.'`);
        await queryRunner.query(`CREATE TYPE "public"."kyc_status_old" AS ENUM('pending', 'aadhaar_verified', 'pan_verified', 'fully_verified', 'liveness_passed', 'failed', 'expired')`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ALTER COLUMN "verification_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ALTER COLUMN "verification_status" TYPE "public"."kyc_status_old" USING "verification_status"::"text"::"public"."kyc_status_old"`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ALTER COLUMN "verification_status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."kyc_records_verification_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."kyc_status_old" RENAME TO "kyc_status"`);
        await queryRunner.query(`COMMENT ON COLUMN "kyc_records"."aadhaar_hash" IS 'SHA-256 of raw Aadhaar number. Never store raw Aadhaar.'`);
        await queryRunner.query(`COMMENT ON COLUMN "documents"."retention_years" IS 'RBI requires 7 years minimum for loan-related documents.'`);
        await queryRunner.query(`COMMENT ON COLUMN "documents"."file_hash" IS 'SHA-256 of original (pre-encryption) file for integrity verification.'`);
        await queryRunner.query(`COMMENT ON COLUMN "documents"."s3_key_encrypted" IS 'AES-256-GCM encrypted S3 object key. Decrypt at app layer to get actual path.'`);
        await queryRunner.query(`CREATE TYPE "public"."doc_type_old" AS ENUM('aadhaar_front', 'aadhaar_back', 'pan', 'bank_statement', 'income_proof', 'itr', 'selfie', 'selfie_with_id', 'business_reg', 'gst_certificate', 'udyam_certificate', 'trade_licence')`);
        await queryRunner.query(`ALTER TABLE "documents" ALTER COLUMN "doc_type" TYPE "public"."doc_type_old" USING "doc_type"::"text"::"public"."doc_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."documents_doc_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."doc_type_old" RENAME TO "doc_type"`);
        await queryRunner.query(`ALTER TABLE "consent_records" ALTER COLUMN "valid_until" SET DEFAULT (now() + '90 days')`);
        await queryRunner.query(`CREATE TYPE "public"."consent_scope_old" AS ENUM('read', 'read_aggregate', 'read_process')`);
        await queryRunner.query(`ALTER TABLE "consent_records" ALTER COLUMN "scope" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "consent_records" ALTER COLUMN "scope" TYPE "public"."consent_scope_old" USING "scope"::"text"::"public"."consent_scope_old"`);
        await queryRunner.query(`ALTER TABLE "consent_records" ALTER COLUMN "scope" SET DEFAULT 'read'`);
        await queryRunner.query(`DROP TYPE "public"."consent_records_scope_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."consent_scope_old" RENAME TO "consent_scope"`);
        await queryRunner.query(`CREATE TYPE "public"."data_source_old" AS ENUM('phone', 'bank', 'ecommerce', 'geolocation', 'merchant', 'psychometric')`);
        await queryRunner.query(`ALTER TABLE "consent_records" ALTER COLUMN "data_source" TYPE "public"."data_source_old" USING "data_source"::"text"::"public"."data_source_old"`);
        await queryRunner.query(`DROP TYPE "public"."consent_records_data_source_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."data_source_old" RENAME TO "data_source"`);
        await queryRunner.query(`ALTER TABLE "cms_questionnaire_questions" ALTER COLUMN "weight" SET DEFAULT 1.0`);
        await queryRunner.query(`ALTER TABLE "cms_loan_products" DROP COLUMN "eligible_risk_bands"`);
        await queryRunner.query(`CREATE TYPE "public"."risk_band" AS ENUM('very_high', 'high', 'medium', 'low', 'very_low')`);
        await queryRunner.query(`ALTER TABLE "cms_loan_products" ADD "eligible_risk_bands" "public"."risk_band" array NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."deletion_scheduled_at" IS 'DPDP Act: data purge at this timestamp (72h after request)'`);
        await queryRunner.query(`CREATE TYPE "public"."user_status_old" AS ENUM('pending', 'active', 'suspended', 'deleted', 'banned')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" TYPE "public"."user_status_old" USING "status"::"text"::"public"."user_status_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_status_old" RENAME TO "user_status"`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_old" AS ENUM('borrower', 'lender', 'admin', 'compliance', 'support')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."user_role_old" USING "role"::"text"::"public"."user_role_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'borrower'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_old" RENAME TO "user_role"`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."full_name_encrypted" IS 'AES-256-GCM: format iv:authtag:ciphertext'`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."mobile_number" IS 'E.164 format Indian mobile. Unique system identifier.'`);
        await queryRunner.query(`COMMENT ON TABLE "users" IS 'Master identity table. No raw PII — all sensitive fields AES-256-GCM encrypted at application layer.'`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" ADD CONSTRAINT "emi_schedules_loan_id_installment_number_key" UNIQUE ("loan_id", "installment_number")`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "documents_user_id_doc_type_is_deleted_key" UNIQUE ("user_id", "doc_type", "is_deleted")`);
        await queryRunner.query(`ALTER TABLE "consent_records" ADD CONSTRAINT "consent_records_user_id_data_source_is_active_key" UNIQUE ("user_id", "data_source", "is_active")`);
        await queryRunner.query(`ALTER TABLE "cms_questionnaire_questions" ADD CONSTRAINT "cms_questionnaire_questions_version_q_number_key" UNIQUE ("version", "q_number")`);
        await queryRunner.query(`ALTER TABLE "cms_content" ADD CONSTRAINT "cms_content_key_locale_key" UNIQUE ("key", "locale")`);
        await queryRunner.query(`ALTER TABLE "repayment_events" ADD CONSTRAINT "repayment_events_amount_paid_check" CHECK ((amount_paid > 0))`);
        await queryRunner.query(`ALTER TABLE "loan_state_transitions" ADD CONSTRAINT "valid_transition" CHECK ((from_state <> to_state))`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" ADD CONSTRAINT "emi_schedules_interest_amount_check" CHECK ((interest_amount >= 0))`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" ADD CONSTRAINT "emi_schedules_principal_amount_check" CHECK ((principal_amount > 0))`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" ADD CONSTRAINT "emi_schedules_installment_number_check" CHECK ((installment_number > 0))`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ADD CONSTRAINT "loan_applications_interest_rate_check" CHECK (((interest_rate >= (0)::numeric) AND (interest_rate <= (100)::numeric)))`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ADD CONSTRAINT "loan_applications_tenure_months_check" CHECK (((tenure_months >= 1) AND (tenure_months <= 60)))`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ADD CONSTRAINT "loan_applications_amount_approved_check" CHECK ((amount_approved > 0))`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ADD CONSTRAINT "loan_applications_amount_requested_check" CHECK (((amount_requested >= 1000) AND (amount_requested <= 50000000)))`);
        await queryRunner.query(`ALTER TABLE "credit_scores" ADD CONSTRAINT "credit_scores_ensemble_pd_check" CHECK (((ensemble_pd >= (0)::numeric) AND (ensemble_pd <= (1)::numeric)))`);
        await queryRunner.query(`ALTER TABLE "credit_scores" ADD CONSTRAINT "credit_scores_model3_stability_check" CHECK (((model3_stability >= (0)::numeric) AND (model3_stability <= (1)::numeric)))`);
        await queryRunner.query(`ALTER TABLE "credit_scores" ADD CONSTRAINT "credit_scores_model2_risk_check" CHECK (((model2_risk >= (0)::numeric) AND (model2_risk <= (1)::numeric)))`);
        await queryRunner.query(`ALTER TABLE "credit_scores" ADD CONSTRAINT "credit_scores_model1_pd_check" CHECK (((model1_pd >= (0)::numeric) AND (model1_pd <= (1)::numeric)))`);
        await queryRunner.query(`ALTER TABLE "credit_scores" ADD CONSTRAINT "credit_scores_score_check" CHECK (((score >= 300) AND (score <= 900)))`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ADD CONSTRAINT "kyc_records_face_match_score_check" CHECK (((face_match_score >= (0)::numeric) AND (face_match_score <= (100)::numeric)))`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "documents_size_bytes_check" CHECK ((size_bytes > 0))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_onboarding_step_check" CHECK (((onboarding_step >= 0) AND (onboarding_step <= 10)))`);
        await queryRunner.query(`CREATE INDEX "idx_notif_retry" ON "notifications" USING btree ("retry_count", "created_at") WHERE ((status = 'failed'::notification_status) AND (retry_count < max_retries))`);
        await queryRunner.query(`CREATE INDEX "idx_notif_status" ON "notifications" USING btree ("status", "scheduled_at") WHERE (status = ANY (ARRAY['queued'::notification_status, 'processing'::notification_status]))`);
        await queryRunner.query(`CREATE INDEX "idx_notif_user" ON "notifications" USING btree ("user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_repayment_unreconciled" ON "repayment_events" USING btree ("paid_at") WHERE (reconciled = false)`);
        await queryRunner.query(`CREATE INDEX "idx_repayment_emi" ON "repayment_events" USING btree ("emi_id") `);
        await queryRunner.query(`CREATE INDEX "idx_repayment_loan" ON "repayment_events" USING btree ("loan_id", "paid_at") `);
        await queryRunner.query(`CREATE INDEX "idx_emi_overdue" ON "emi_schedules" USING btree ("due_date", "days_past_due") WHERE ((status = 'pending'::emi_status) AND (days_past_due > 0))`);
        await queryRunner.query(`CREATE INDEX "idx_emi_due" ON "emi_schedules" USING btree ("due_date", "status") WHERE (status = 'pending'::emi_status)`);
        await queryRunner.query(`CREATE INDEX "idx_emi_loan" ON "emi_schedules" USING btree ("loan_id", "installment_number") `);
        await queryRunner.query(`CREATE INDEX "idx_loans_band" ON "loan_applications" USING btree ("amount_requested", "state", "interest_rate") `);
        await queryRunner.query(`CREATE INDEX "idx_loans_active" ON "loan_applications" USING btree ("user_id") WHERE (state <> ALL (ARRAY['rejected'::loan_state, 'closed'::loan_state, 'written_off'::loan_state, 'draft'::loan_state]))`);
        await queryRunner.query(`CREATE INDEX "idx_loans_submitted" ON "loan_applications" USING btree ("applied_at") WHERE (state = 'submitted'::loan_state)`);
        await queryRunner.query(`CREATE INDEX "idx_loans_lender_state" ON "loan_applications" USING btree ("lender_id", "state", "applied_at") WHERE (lender_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_loans_user_state" ON "loan_applications" USING btree ("user_id", "state") `);
        await queryRunner.query(`CREATE INDEX "idx_scores_model" ON "credit_scores" USING btree ("model_version", "generated_at") `);
        await queryRunner.query(`CREATE INDEX "idx_scores_band" ON "credit_scores" USING btree ("risk_band", "generated_at") `);
        await queryRunner.query(`CREATE INDEX "idx_scores_user_date" ON "credit_scores" USING btree ("user_id", "generated_at") `);
        await queryRunner.query(`CREATE INDEX "idx_kyc_status" ON "kyc_records" USING btree ("verification_status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_kyc_user" ON "kyc_records" USING btree ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_docs_hash" ON "documents" USING btree ("file_hash") WHERE (is_deleted = false)`);
        await queryRunner.query(`CREATE INDEX "idx_docs_hard_delete" ON "documents" USING btree ("hard_delete_at") WHERE ((hard_delete_at IS NOT NULL) AND (hard_deleted_at IS NULL))`);
        await queryRunner.query(`CREATE INDEX "idx_docs_user_type" ON "documents" USING btree ("user_id", "doc_type") WHERE (is_deleted = false)`);
        await queryRunner.query(`CREATE INDEX "idx_consent_expiry" ON "consent_records" USING btree ("valid_until") WHERE (is_active = true)`);
        await queryRunner.query(`CREATE INDEX "idx_consent_deletion" ON "consent_records" USING btree ("data_deletion_scheduled_at") WHERE ((data_deletion_scheduled_at IS NOT NULL) AND (data_deleted_at IS NULL))`);
        await queryRunner.query(`CREATE INDEX "idx_consent_user_source" ON "consent_records" USING btree ("user_id", "data_source", "is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_faq_category_locale" ON "cms_faqs" USING btree ("category", "locale") WHERE (is_active = true)`);
        await queryRunner.query(`CREATE INDEX "idx_cms_namespace" ON "cms_content" USING btree ("locale", "namespace") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_cms_key_locale" ON "cms_content" USING btree ("key", "locale") WHERE (is_active = true)`);
        await queryRunner.query(`CREATE INDEX "idx_sessions_expires" ON "sessions" USING btree ("expires_at") WHERE (is_revoked = false)`);
        await queryRunner.query(`CREATE INDEX "idx_sessions_user_active" ON "sessions" USING btree ("user_id", "expires_at") WHERE (is_revoked = false)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_sessions_refresh" ON "sessions" USING btree ("refresh_token_hash") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_sessions_jti" ON "sessions" USING btree ("jwt_jti") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_action" ON "audit_logs" USING btree ("action", "logged_at") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_actor" ON "audit_logs" USING btree ("actor_id", "logged_at") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_entity" ON "audit_logs" USING btree ("entity_type", "entity_id", "logged_at") `);
        await queryRunner.query(`CREATE INDEX "idx_users_deletion_scheduled" ON "users" USING btree ("deletion_scheduled_at") WHERE ((deletion_scheduled_at IS NOT NULL) AND (status <> 'deleted'::user_status))`);
        await queryRunner.query(`CREATE INDEX "idx_users_created_at" ON "users" USING btree ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_users_role_status" ON "users" USING btree ("role", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_users_mobile" ON "users" USING btree ("mobile_number") `);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repayment_events" ADD CONSTRAINT "repayment_events_loan_id_fkey" FOREIGN KEY ("loan_id") REFERENCES "loan_applications"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repayment_events" ADD CONSTRAINT "repayment_events_emi_id_fkey" FOREIGN KEY ("emi_id") REFERENCES "emi_schedules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_state_transitions" ADD CONSTRAINT "loan_state_transitions_loan_id_fkey" FOREIGN KEY ("loan_id") REFERENCES "loan_applications"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_state_transitions" ADD CONSTRAINT "loan_state_transitions_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "emi_schedules" ADD CONSTRAINT "emi_schedules_loan_id_fkey" FOREIGN KEY ("loan_id") REFERENCES "loan_applications"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ADD CONSTRAINT "loan_applications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ADD CONSTRAINT "loan_applications_score_id_fkey" FOREIGN KEY ("score_id") REFERENCES "credit_scores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ADD CONSTRAINT "loan_applications_lender_id_fkey" FOREIGN KEY ("lender_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_applications" ADD CONSTRAINT "loan_applications_second_approver_id_fkey" FOREIGN KEY ("second_approver_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_scores" ADD CONSTRAINT "credit_scores_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ADD CONSTRAINT "kyc_records_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "documents_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "documents_verified_by_fkey" FOREIGN KEY ("verified_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consent_records" ADD CONSTRAINT "consent_records_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cms_content" ADD CONSTRAINT "cms_content_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cms_content" ADD CONSTRAINT "cms_content_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_referred_by_id_fkey" FOREIGN KEY ("referred_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
